### ISSUE TITLE
Invalid checksum

### ISSUE THREAD

**Issue by nerg4l** [HDT3213/rdb#35]
I modified this library to encode an RDB with version 5 header. In this case, Redis validates the checksum and the validation fails.

https://github.com/HDT3213/rdb/blob/d16ee7797e5f2d00be381c2b1981a52090a29ab9/core/encoder.go#L94

This library uses the default crc64 implementation with the ISO polynomial but Redis uses crcr-64-jones which produces different checksum values.

**Comment by HDT3213** [comment]
Got it, I'll try to fix this

**Comment by HDT3213** [comment]
@nerg4l fixed in e9eadea

**Comment by nerg4l** [comment]
@HDT3213 I checked and I still get `RDB CRC error`.

```
1:C 08 May 2024 13:27:14.803 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2024-05-08T13:27:14.804150334Z 1:C 08 May 2024 13:27:14.803 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
2024-05-08T13:27:14.804152043Z 1:C 08 May 2024 13:27:14.803 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
2024-05-08T13:27:14.804397084Z 1:M 08 May 2024 13:27:14.804 * monotonic clock: POSIX clock_gettime
2024-05-08T13:27:14.804780209Z 1:M 08 May 2024 13:27:14.804 * Running mode=standalone, port=6379.
2024-05-08T13:27:14.806011251Z 1:M 08 May 2024 13:27:14.805 * Server initialized
2024-05-08T13:27:14.808358209Z 1:M 08 May 2024 13:27:14.808 # Wrong RDB checksum expected: (a579b9fa5df302f2) but got (49ec48272c704d85). Aborting now.
2024-05-08T13:27:14.808368543Z 1:M 08 May 2024 13:27:14.808 # Internal error in RDB reading offset 0, function at rdb.c:3341 -> RDB CRC error
2024-05-08T13:27:14.810147793Z [offset 0] Checking RDB file dump.rdb
2024-05-08T13:27:14.810170793Z [offset 11] Selecting DB ID 0
2024-05-08T13:27:14.810172959Z --- RDB ERROR DETECTED ---
2024-05-08T13:27:14.810173959Z [offset 201056] RDB CRC error
2024-05-08T13:27:14.810174876Z [additional info] While doing: check-sum
2024-05-08T13:27:14.810175793Z [info] 4 keys read
2024-05-08T13:27:14.810176709Z [info] 0 expires
2024-05-08T13:27:14.810177543Z [info] 0 already expired
```

From what I can tell, the Go implementation of crc64 works a bit differently. I can create a PR to add an internal package with the correct implementation.

**Comment by HDT3213** [comment]
Your work is very welcome, Just go ahead

**Comment by nerg4l** [comment]
Success with the PR

```
1:C 09 May 2024 20:25:29.463 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2024-05-09T20:25:29.464352510Z 1:C 09 May 2024 20:25:29.463 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
2024-05-09T20:25:29.464357552Z 1:C 09 May 2024 20:25:29.463 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
2024-05-09T20:25:29.464360302Z 1:M 09 May 2024 20:25:29.464 * monotonic clock: POSIX clock_gettime
2024-05-09T20:25:29.465198010Z 1:M 09 May 2024 20:25:29.465 * Running mode=standalone, port=6379.
2024-05-09T20:25:29.465852760Z 1:M 09 May 2024 20:25:29.465 * Server initialized
2024-05-09T20:25:29.466322885Z 1:M 09 May 2024 20:25:29.466 * Loading RDB produced by version 7.2.4
2024-05-09T20:25:29.466335468Z 1:M 09 May 2024 20:25:29.466 * RDB age 212 seconds
2024-05-09T20:25:29.466336843Z 1:M 09 May 2024 20:25:29.466 * RDB memory usage when created 1.12 Mb
2024-05-09T20:25:29.466950552Z 1:M 09 May 2024 20:25:29.466 * Done loading RDB, keys loaded: 4, keys expired: 0.
2024-05-09T20:25:29.467149968Z 1:M 09 May 2024 20:25:29.467 * DB loaded from disk: 0.001 seconds
2024-05-09T20:25:29.467158427Z 1:M 09 May 2024 20:25:29.467 * Ready to accept connections tcp
```
